language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
  - docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix --show-progress=estimating --verbose --rules=@Symfony,@PSR2
  - docker run --rm -v $PWD:/app phpqa/security-checker security:check